name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Run no_std tests
      run: cargo test --no-default-features
    - name: Run std tests
      run: cargo test --features std,serde,schemars --doc
